### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by hugglesfox** [slackhq/nebula#101]
It would be great if Nebula provided deb and rpm packages to simplify the install and upgrade process.

**Comment by SaigyoujiYuyuko233** [comment]
agree! :) but the installation is simple. It just is a simple runnable file.

**Comment by coderobe** [comment]
These should ideally be provided by downstream packagers of the relevant ecosystems to prevent incompatibilities and ensure distribution-local packaging standards - [NixOS](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/nebula/default.nix) and [Arch Linux](https://www.archlinux.org/packages/community/x86_64/nebula/) are already doing that.
Consider bringing it up to the package maintainer(s) of the relevant distributions

**Comment by rawdigits** [comment]
I brought this in a comment on one of the arstechnica articles about nebula as well. We'd definitely prefer if other folks who enjoy using nebula might take up the task of packaging it for various distros/platforms, as @coderobe has done for Arch.

https://arstechnica.com/gadgets/2019/12/how-to-set-up-your-own-nebula-mesh-vpn-step-by-step/?comments=1&post=38425931

**Comment by toonsevrin** [comment]
I'll write a snapcraft package, hopefully this can then be CDed with the [slack publisher](https://snapcraft.io/slack).

**Comment by hlovdal** [comment]
I have created  [rpm packages for my own usage](https://github.com/hlovdal/nebula-overlay-networking) that I have used on all my Fedora/Centos machines for a couple of months now. With those it is only install package, edit configuration file and then start and enable service.

(Now my package is "cheating" in the build process by just pulling the release binaries from this repository, which is why I have not made any pull requests yet.)

But related to this, I think just `nebula` is a very poor package name since

1. It is not very descriptive.
2. There exists other existing packages already named [nebula](https://rpmfind.net/linux/RPM/fedora/34/x86_64/n/nebula-0.2.3-24.fc34.x86_64.html).

I chose to name the package `nebula-overlay-networking` to avoid these issues.

Now that there exists a [pull request for a Debian package](https://github.com/slackhq/nebula/pull/514) I think it would be good to have a discussion on package name to avoid unnecessary naming fragmentation (like for example [`kdeconnect-kde`, `kdeconnect-plasma`, `kdeconnect` or `kde-connect`](https://invent.kde.org/network/kdeconnect-kde#on-linux)).

Any maintainer opinions on package names?

**Comment by hlovdal** [comment]
Related [FreeBSD pull request](https://github.com/slackhq/nebula/pull/350).

**Comment by jdoss** [comment]
>     2. There exists other existing packages already named [nebula](https://rpmfind.net/linux/RPM/fedora/34/x86_64/n/nebula-0.2.3-24.fc34.x86_64.html).

This `nebula' software is no longer being maintained upstream and that package is being retired. I am working with the current maintainer of the `nebula` package in Fedora and EPEL to possibly take over the nebula in Fedora and EPEL name once EPEL 8 is no longer supported.

**Comment by jasikpark** [comment]
Created #630 since someone added nebula to homebrew complete w/ a service setup

**Comment by JohnMaguire** [comment]
Hi there - we'd love to see packages for various distros but this is ultimately something to take up with the distro maintainers themselves.

I know [Arch Linux](https://archlinux.org/packages/community/x86_64/nebula/), [https://formulae.brew.sh/formula/nebula](Homebrew) and [Debian](https://tracker.debian.org/pkg/nebula) have packages, and there appears to be a [snap](https://snapcraft.io/nebula) package as well.
