### ISSUE TITLE
Add Openwrt Support - Feature Request

### ISSUE THREAD

**Issue by eldadh** [slackhq/nebula#118]
Add Openwrt Support - Feature Request

**Comment by nbrownus** [comment]
Can you expand on what level of support you are looking for?

**Comment by nfam** [comment]
@nbrownus I think a nebula executable on OpenWRT would be enough, since OpenWRT is already the gateway of network.

**Use case 1** a small business deploys an application server (for internal staff only) on cloud, then configures an OpenWRT connected to the server through nebula. Any employee's iPad connected to the OpenWRT is able to access to the application server. This will free us from setting up app and cert on each iPad (which has not been released yet), and laptop.

**Use case 2** This is especially helpful for IoT. All tiny devices in our house connected to (or bridged via a hub to) a central OpenWRT, we can monitor and control them far away (through `unsafe_route` if needed) without employing the vendors' cloud service (cost and risk of data leakage).

**Comment by nfam** [comment]
@eldadh Did you try the vanilla `linux-amd64` or `linux-arm` on your OpenWRT?

**Comment by eldadh** [comment]
Most ipenwrt home routers are with mips/ramips cpu architecture, so nor arm or x86 would work.
And crosscompiling is more then i can chew at the moment

**Comment by nfam** [comment]
`bin-mips` is already there in Makefile. If downloading Golang and type `make bin-mips` are too hard for you, then wait till version 1.1 released.

**Comment by rawdigits** [comment]
as noted, we will release mips binaries with 1.1+, and you are free to build it from source in the meantime.

**Comment by venkatchimata** [comment]
@nfam @eldadh You can try this: https://www.nearhop.com/download . It addresses both the usecases that nfam mentioned.
