### ISSUE TITLE
Idea: Drop data encryption for connection in the same zone

### ISSUE THREAD

**Issue by nfam** [slackhq/nebula#137]
Nebula helps to seamlessly connect computers anywhere in the world. However, a group of machines likely stay in the same location (server rack, server cluster, data center,...), where data encryption is not necessary.

Fortunately, since the network topology is peer-to-peer (of a mesh), nebula is able to determine whether the connection between 2 particular nodes should be encrypted. I suggest to add an optional attribute (let's say `zone`) to certificates generated by `nebula-cert`.

1. If `zone` of a node is not provided, any connection from and to the node will be encrypted (as it is).
2. If 2 nodes' `zone` are different, the connection between them will be encrypted.
3. If 2 nodes' `zone` are the same, the connection between them will not be encrypted.

With this, we can apply nebula as overlay network for the whole distributed system without performance penalty (or at least within acceptable rate) in local clusters.

**Comment by rawdigits** [comment]
We've actually spec'd this out and I wrote some test code. It is very do-able, but since I/we don't have a use case I don't know if we will ever pursue it. A problem this introduces is "what do you do if a node roams to a link that is less secure?".

Another big reason we haven't done this is because most of the CPU time for nebula is spent doing syscalls, not encryption. Because we run in userspace, we do a lot of syscalls to move data between kernelspace and userspace when sending packets. New kernel constructs like XDP and frameworks like DPDK can allow us to eliminate syscalls but come with their own tradeoffs. I don't have the numbers at hand, but I think crypto is less than 20% of the work we do. (will check and update if i'm way wrong)

the note about dpdk/xdp is #5

**Comment by nfam** [comment]
Thank you for the information.

I guess CPU time of encryption (due to acceleration) is far less than `a lot of syscalls to move data between kernelspace and userspace`. The gain is too little, I don't think we need to consider this in the moment.

**Comment by rawdigits** [comment]
Agreed. Going to close this one for now, but good thought and appreciate the feedback!
