### ISSUE TITLE
Keeping selinux enabled with Nebula, service fails

### ISSUE THREAD

**Issue by dverdonschot** [slackhq/nebula#158]
I am trying to create a selinux policy for Nebula to ignore events to make sure I can keep selinux active on my servers while running Nebula. It mostly works, but the Nebula service fails on a reboot.
When I first run Nebula manually, or I set selinux to permissive I can start the service. If I then enable selinux I can restart as expected.

in journalctl -xe I see the following message:
level=fatal msg="no such device"

Looks like selinux is still preventing the creation of the network interface for Nebula, and a manual start of Nebula or a start of the service with selinux permissive resolves it.

Environment: Centos 8

## Steps taken

Created a service for Nebula, like in the example git repo.

```
cat /usr/lib/systemd/system/nebula.service
[Unit]
Description=nebula
Wants=basic.target
After=basic.target network.target

[Service]
SyslogIdentifier=nebula
StandardOutput=syslog
StandardError=syslog
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/nebula -config /etc/nebula/config.yml
Restart=always

[Install]
WantedBy=multi-user.target
```

Created a policy with audit2allow and loaded it.

```
grep nebula /var/log/audit/audit.log | audit2allow -M nebulalocal 
semodule -i nebulalocal.pp
semodule -l
```

Now all invalid selinux AVC's are allowed in current policy, no errors left:

```
*** Invalid AVC allowed in current policy ***

type=AVC msg=audit(1578750253.305:191): avc:  denied  { execute } for  pid=16679 comm="(nebula)" name="nebula" dev="dm-0" ino=51248653 scontext=system_u:system_r:init_t:s0 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=0
 
**** Invalid AVC allowed in current policy ***

100% done
found 0 alerts in /var/log/audit/audit.log
```

But when I try to start the service it fails

``` 
systemctl status nebula
● nebula.service - nebula
   Loaded: loaded (/usr/lib/systemd/system/nebula.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2020-01-11 16:07:50 CET; 22s ago
  Process: 832 ExecStart=/usr/local/bin/nebula -config /etc/nebula/config.yml (code=exited, status=1/FAILURE)
 Main PID: 832 (code=exited, status=1/FAILURE)
```

If I then set selinux to permissive I can start the service, and even when I turn it back to enforcing, Nebula will keep working and can be restarted

```
setenforce 0
systemctl start nebula
setenforce 1
systemctl restat nebula <-- no problem
```

I can also manually start Nebula on start up, and after that I can start the service using enforcing selinux.

**Comment by nbrownus** [comment]
Fairly certain if this is an issue standing up the tun device. Testing with `master` would give a more helpful error message. I'm not personally that experienced with selinux but if you can provide the rules you are using, I can try to help debug.

**Comment by twnk** [comment]
I was able to solve this, additionally running nebula as an unprivileged user. See also #300

This is the policy generated by sepolicy generate, with the additions i found necessary using audit2allow. 
```
 ########################################
#
# Declarations
#

type nebula_t;
type nebula_exec_t;
init_daemon_domain(nebula_t, nebula_exec_t)

# permissive nebula_t;

########################################
#
# nebula local policy
#
allow nebula_t self:fifo_file rw_fifo_file_perms;
allow nebula_t self:unix_stream_socket create_stream_socket_perms;

domain_use_interactive_fds(nebula_t)

files_read_etc_files(nebula_t)

miscfiles_read_localization(nebula_t)

sysnet_dns_name_resolve(nebula_t)

# Added from audit2allow
allow nebula_t self:capability { net_bind_service net_admin };
allow nebula_t self:netlink_route_socket nlmsg_write;
allow nebula_t self:tun_socket create;
corenet_rw_tun_tap_dev(nebula_t)
corenet_udp_bind_dns_port(nebula_t)
corenet_udp_bind_generic_node(nebula_t)
corenet_udp_bind_generic_port(nebula_t)
dev_read_sysfs(nebula_t)
```

Of specific note is `allow nebula_t self:capability { net_admin };`. This rule was not suggested by audit2allow and did not generate any warnings in audit logs when in permissive mode. But without it, switching to enforcing mode would stop nebula from starting.

Additional details, `cap_net_bind_service,cap_net_admin+ei` on the nebula binary and then in `nebula.service`
```
...
[Service]
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
User=nebula
Group=nebula
...
``` 
If you're running nebula as a root user rather than an unprivileged service user, you may not need the capabilities. Hopefully this is helpful @dverdonschot

**Comment by twnk** [comment]
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_selinux/writing-a-custom-selinux-policy_using-selinux I found this particularly helpful but had to do a lot of experimentation in addition. This is not a complete selinux policy - a full policy should probably define file types for the nebula config, nebula certificate key and so on, so that these files are more heavily restricted rather than left as `etc_t` and relying singularly on file permissions to prevent other processes from reading them.

**Comment by JohnMaguire** [comment]
Closing this out as it appears to be solved above. If you continue to run into issues please open a new ticket.
