### ISSUE TITLE
-out-crt and -out-key should be directories

### ISSUE THREAD

**Issue by jwallden** [slackhq/nebula#193]
Doing 
`./nebula-cert sign -name test-node -out-crt test-node/ -out-key test-node/ -ip 192.168.100.100/24`
fails because -out-crt and -out-key is supposed to be paths with filenames. However, since we specify the -name argument (that will be the name of the cert and key) -out-crt and -out-key should be the directories where you want the certs to be written to.

I ran in to this issue when working on creating a snap for Nebula. Since I'm aiming for it being run in strict confinement I need to hardcode the directories where certs are created

**Comment by wadey** [comment]
If you want to write to a folder, just make the filename explicit, like this:

```
./nebula-cert sign -name test-node -out-crt test-node/test-node.crt -out-key test-node/test-node.key ...
```

**Comment by jwallden** [comment]
Thank you for answering.
I know that I can use an explicit filename, as in the example above. However, what I would like is to state the directories with -out-crt and -out-key and use the value from -name as the cert and key names.

**Comment by nbrownus** [comment]
I'm fairly opposed to this as you have a number of methods to achieve what you are looking for without adding another mode to `nebula-cert`.

1. Change directories before running `nebula-cert` to the directory you want the material to live in. 
2. Since you are already providing a name argument providing the final path in `out-crt` and `-out-key` should be fairly simple. Using some automation tool like chef/puppet/ansible should make this a non issue

I certainly realize this would help your specific workflow but adding another mode to how `nebula-cert` behaves makes the tool even more complex.

**Comment by jwallden** [comment]
Hi,
Apologies for the late response.

To me it seems a bit awkward that you give a name (with `-name`) for the cert but then you have to give the full path including the name when stating where to place the certs.
My suggestion is not to add another mode but rather change `-out-crt` and `-out-key` to be directories and then append `-name` to it.
In my opinion this would give a little more flexibility, for example when trying to package Nebula as a snap that doesn't require classic confinement ;)
