### ISSUE TITLE
LDAP not working over nebula network?

### ISSUE THREAD

**Issue by mxc** [slackhq/nebula#228]
Hi all,

I know this is not a forum but can't find the right place to post this and it might be an issue :) I have set up my nebula network and I can ping, ssh and https from my server in the data centre to an internal server behind the nat firewall on the lan. However when I try to query the ldap server it just hangs before the connection times out. The firewall rules have been enabled for 389 and the connection uses with starttls.

Performing a tcpdump for port 4242 on the ldap server, on the LAN, on the physical network card shows no incoming connections and neither does a tcpdump on the nebula interface for the vip of the external server. It appears packets simple don't get to the lan host.
I have added tcp and udp firewall rules just in case with no change.

Any suggestions of what I could try to troubleshoot this issue? Does it sound like it could be a config issue or some weird network issue with ldap and the firewall?

thanks

**Comment by mxc** [comment]
I found the issue. For some reason if I have more than one group listed nebula firewall doesn't appear to work. Will continue to investigate.

**Comment by fm407** [comment]
> I found the issue. For some reason if I have more than one group listed nebula firewall doesn't appear to work. Will continue to investigate.

The host you are writing firewall rules for has to be in ALL groups in order for multi-group to work. I do not know if this is expected behavior or a bug. So for example, is Server1 is in Group1 and you write a rule with groups on Server2 to allow `groups: Group1, Group2` it wont work unless Server1 is in both groups.

I had the same issue, you can either resolve it by recreating all the certs with all the groups in it or creating multiple rules using `group:` and listing one group per ruleblock, instead of `groups:`.

Hope it makes sense, maybe someone from the dev team can chime in.

**Comment by wadey** [comment]
Yes, if multiple groups are listed in a firewall rule, they all have to match. This is described in the example config:

https://github.com/slackhq/nebula/blob/v1.2.0/examples/config.yml#L205
