### ISSUE TITLE
Question: How would one use failover?

### ISSUE THREAD

**Issue by SolSoCoG** [slackhq/nebula#282]
Hello,

I got two servers I'd like to use as lighthouses,
I managed creating a connection between server A or B and client, all good.
However I'd like to use server A as main server and B as failover,
preferrably via one hostmap entry if possible.

Best regards,
Alex

**Comment by bonedaddy** [comment]
At the moment I don't think this is possible, you can list multiple lighthouses and if i understand correctly, nebula will try to use whatever lighthouse is available. Outside of nebula however you could use a load balancer and have that sit infront of your lighthouses.

**Comment by motorious-hub** [comment]
Dear Editor: Gay City News

The ONLY issue of your paper I have ever read, was the one entitled: “Impeach Rumsfeld”, where there were photos of the Iraqi prisoners being tortured (Private Lindy EnglandPin auf Disturbing Things , in which all of the senior officers of the US Military: Don’t Ask, Don’t Tell were listed by name. 


	
Pin auf Disturbing Things
10.08.2012 - Lynndie England holding a leash attached to a prisoner at Abu Ghraib prison in Iraq were many prisoners were tortured and abused.


The last time I saw Donald Rumsfeld, was at the Brooklyn Public Library, Grand Army Plaza:

Each ACCOUNT, was allowed to use the computers for an hour at a time. There are camera strategically located throughout the building.

That day, Lindsay strolled in casually, and slipped into the seat next to mine. I immediately did a search for “Lindsay Lohan” after which images of her filled the screen. She casually looked over and said: “So you like Lindsay Lohan?” (No answer) some people say that I look like her (Actually, I think you’re prettier 😘) She looked over my shoulder several times, then sighed out and walked out of the library. 

Wolé Fayemi v Kings County, Mustafa, Jenardinan et al

Arrived un a private ambulette ordered by Jedediah Burack. Picked up at 280 E21st Street, 1B:  

Dr Jinardinan. What should I call you?
DINO: Dino
Dr J: Why do you want to be called that? 
DINO: are you willing to sign a Non Disclosure Agreement?
Dr. J: ...Very well. 

You will spend the next 72 hours sleeping on the floor of the overcrowded Emergency Room, which is infested with cockroaches and mice, during which time Sukanye of WB11 news, will watch you as you’re crying (laughing), and then you will he visited by Sarah, who will ask you to sign a deposition re: Class Action Lawsuit. You will have a brief meeting with a #PsychobabblebullshitArtist, who will ask you to sign the admission papers, while your brothers high school classmate, Joel Abramson, watches silently. 

Dr J: I will assign then assign you to Dr. Colin Powell, III’s son: Director of the FCC, and you will spend the next 7 months there against your will, force injected Haloperidol 3 times a day. You’ll probably pass out and drool, when you’re not screaming at the top of your lungs and telling crazy stories about your girlfriend in San Francisco before your ex-wife: bit.ly/jailbait_juaperez. 

Ever since I relayed, on Google Plus, that OBVIOUSLY, the Iraq War was just like Cosovo.

As The CEO of Hard Hat Bid explained it to me, approximately 6 months before the 9/11 bombings, “war is business”. We tear things down, so that we can profit from the contracts to rebuild”

Curiously, after the bombings, the US was hesitant about sending troops in during the summer (it was too hot they said)...


Wolé M. Fayemi
Motorious Automotive, llc

347-499-2253

**Comment by ibehren1** [comment]
Why one or the other, both is better.

As I understand, when both are defined in the config they are both used and provides more redundancy.  This is what I am currently running -- 2 lighthouses in separate AWS regions and 6 clients, some in the AWS regions and 1 as gateway with unsafe routes on my home LAN -- all have both lighthouses in the config.  I can stop either lighthouse at anytime and traffic keeps flowing between the nodes.

**Comment by JohnMaguire** [comment]
Since there hasn't been any recent discussion on this ticket explaining the motivations for failover (active/passive, as opposed to active/active), I'm closing this issue out as stale/not planned.
