### ISSUE TITLE
static link binary for Linux

### ISSUE THREAD

**Issue by hronro** [slackhq/nebula#295]
I just found nebula for Linux is not static linked (it's weird since nebula is written in Go), and I can not run it on Alpine Linux.

Shipping a static link binary would helped a lot.

**Comment by MikePadge** [comment]
Copypasta from Stack

By default, if using the net package a build will likely produce a binary with some dynamic linking, e.g. to libc. You can inspect dynamically vs. statically link by viewing the result of ldd output.bin

There are two solutions I've come across:

Disable CGO, via CGO_ENABLED=0
Force the use of the Go implementation of net dependencies, netgo via go build -tags netgo -a -v, this is implemented for a certain platforms
From https://golang.org/doc/go1.2:

The net package requires cgo by default because the host operating system must in general mediate network call setup. On some systems, though, it is possible to use the network without cgo, and useful to do so, for instance to avoid dynamic linking. The new build tag netgo (off by default) allows the construction of a net package in pure Go on those systems where it is possible.

The above assumes that the only CGO dependency is the standard library's net package.

**Comment by RealOrangeOne** [comment]
FYI looks like Nebula is now available in Alpine's package repo in v3.13

https://pkgs.alpinelinux.org/package/v3.13/community/x86_64/nebula
