### ISSUE TITLE
Running multiple instances on Windows

### ISSUE THREAD

**Issue by caguiclajmg** [slackhq/nebula#379]
I can't seem to be able to run more than 1 instance of Nebula on Windows at a time.

I have 2 sets of config files but whichever gets started last keeps getting `Activate failed: A device attached to the system is not functioning.` when starting the second instance.

I already have multiple TUN devices and device names are properly specified in the config file under `tun.dev`, any ideas?

**Comment by jdknezek** [comment]
See https://github.com/slackhq/nebula/blob/master/tun_windows.go#L43

On Windows, rather than using the device name from the config, nebula uses a fixed hardware ID, so if I understand correctly you can only ever have one instance running on Windows.

There are issues & PRs about moving from tap-win64 to wintun (from the Wireguard project) which may address this in the future.

**Comment by jdknezek** [comment]
If you can build from source this may be a 2-line fix - it seems to work on my Windows machine:

https://github.com/jdknezek/nebula/commit/48b8e4c6b59e4021b852626fd179e1296be378f7

**Comment by caguiclajmg** [comment]
Sorry took me so long, to get to it; but can confirm this works great.

I'm gonna close this now since there seems to be already old PRs and Issues which address this specifically, namely https://github.com/slackhq/nebula/pull/293 and https://github.com/slackhq/nebula/issues/70
