### ISSUE TITLE
Allow single sign on

### ISSUE THREAD

**Issue by MrAvana** [slackhq/nebula#380]
It would be great if single sign on is implemented. For example Google sign in.

**Comment by jimpea21** [comment]
Given that the current Nebula design has zero provision for authentication sources outside the generated certificates, I wouldn't expect to see this any time soon.

Tailscale does this is if you really want it though.

**Comment by ieugen** [comment]
I think we can leverage single sign on for generating user certificates. 
It will require a server component that can act as a client for identity services (google, facebook, any Oauth/OpenID Connect provider). 

The server will also manage a map of user-id => groups and other information. 
Server has access to a private key to generate certificates and maybe a template.

User logs into app using auth provider (Google, Fb, whatever). 
User has access to a form that he can use to generate a cert for him or even the full configuration with included certs.

If  nebula has a concept of certificate request, user might be able to generate a private key himself and use the service to sign it. 
This way private key does not leave user computer.

**Comment by unreality** [comment]
At the risk of self-promotion, I created a project that allows SSO into a mesh: https://github.com/unreality/nebula-mesh-admin (a detailed howto is available at https://blog.unreality.xyz/post/nebula-sso/ )

**Comment by mannp** [comment]
@unreality new to nebula but any reason your project couldn't be a PR rather than a separate project?

**Comment by JohnMaguire** [comment]
Hi @MrAvana -

Thanks for the feature request. As hinted at above, building Single Sign-On for Nebula is non-trivial. This would require an HTTP endpoint for receiving SSO messages as well as a secure signing oracle for issuing certificates.

The Nebula project is focused on providing highly performant and security tunneling between your devices, with simplicity as a design goal. In order to ensure a focus on security and performance it's important to keep the surface area of Nebula low.

The project's stance is that key management and signing oracles are outside of the scope of Nebula and should be implemented separately.

You may want to take a look [Defined Networking](https://defined.net) [full disclosure: I am en employee] for a hosted offering that handles key management and authentication for you. Alternatively, [unreality/nebula-mesh-admin](https://github.com/unreality/nebula-mesh-admin) and (b177y/starship)[https://github.com/b177y/starship] are open-source projects in this vein.
