### ISSUE TITLE
Nebula iOS app not able to reach any other nodes

### ISSUE THREAD

**Issue by FDrebin** [slackhq/nebula#435]
I've installed a lighthouse in our AWS environment, I have nodes on Windows and Linux reporting in successfully and reachable via both ping and to reach things such as RDP and and Webmin. The one thing I am unable to do is via iOS, I took the certificate the phone generated, sent that to my Nebula lighthouse and signed it using the appropriate command, took the crt and placed it onto the phone, imported it and my lighthouse CA and entered the lighthouse external_DNS_Name:4242 .

When I connect the iOS app, it shows Active 0 | Pending 0 , so to me it does not appear to be properly connecting..but I did not see any documentation on troubleshooting or where to start troubleshooting.

**Comment by FDrebin** [comment]
It looks like if I am on a WiFi network it works perfectly fine and is able to open the tunnel to the lighthouse and the node I want successfully. When on LTE, it opens the tunnel to the lighthouse successfully but the node I want stays as pending.

**Comment by nbrownus** [comment]
The initial behavior of having no connections is expected on the default mobile config. The lighthouse update interval defaults to 0 on there, which means no tunnels are stood up until you interact with another ip on your mesh (ping a host, visit a website over nebula, etc). On non mobile clients, the lighthouse tunnels are created at boot. We do this to conserve battery, the setting lives under the advanced tab in your site config if you would like to change it.

The next issue could be caused by a number of things. The two main things that will help regardless of your setup are:
- Set `punchy.respond` to true on all your non mobile nodes.
- Ensure your lighthouse is not within a network local to any of your other nodes.

**Comment by FDrebin** [comment]
Understood, thank you. You are correct, once I started browsing to the Nebula IP's of the devices it spun up the tunnels. The Nebula lighthouse is actually unreachable internally and is an internet only object, so all devices that are connecting to the lighthouse are indeed external/internet sources, I am looking into the punch.respond so I appreciate that.

**Comment by zenithbb** [comment]
@nbrownus : thanks for the indication, but is it possible  to set mobile node with punchy.respond = true?
