### ISSUE TITLE
JIT/PAM Support?

### ISSUE THREAD

**Issue by dark1587** [slackhq/nebula#477]
Is there any documentation or methods to implement Nebula for JIT access? Basically having Nebula act as a PAM versus having to rely on PAM solutions such as CyberArk _(shudders)._

Use case:

I want to allow Bob the user to access one or more servers via SSH, but only for a certain period of time (let's say 24 hours). 

Additional notes:
I understand there would have be some lifting on my end - such as creating a service/web portal to request access. After that point, how quickly could Nebula revoke access and update its configuration to blocklist the existing cert? Is there a way to potentially tweak how long a certificate would last before expiring? And could a user request a new cert to re-allow access?

**Comment by JohnMaguire** [comment]
Apologies for the late response here.

The Nebula project is focused on providing highly performant and security tunneling between your devices, with simplicity as a design goal. In order to ensure a focus on security and performance it's important to keep the surface area of Nebula low. The project's stance is that key management and signing oracles are outside of the scope of Nebula and should be implemented as separate projects.
