### ISSUE TITLE
Handshake timed out error  (1.4.0 - MacOS)

### ISSUE THREAD

**Issue by resuscv** [slackhq/nebula#508]
I've noticed that Nebula (client/non-lighthouse) is reporting handshake timed out errors constantly after initially connecting without a problem.  My clients connect to the (remote) lighthouse and then it starts timing out after about 2 minutes.  This happens constantly.  It **appears** to happen for 1.4.0 but not 1.3.0.

*HOWEVER*, when I use the nebula network the handshake stops timing out.  For a bit.  Then it times out again.

- The lighthouse host is reachable - I have long running ssh tunnels connected.
- I've regenerated my CAs and host keys - it's still a problem
- I've changed my IP ranges and my CIDRs
- I've tried using both IP addresses and domain names for my lighthouse
 
Still is a problem.

I've tested clients on Linux, MacOS and Android.  It consistently happens on MacOS.  I can't consistently reproduce in Android.

Lighthouse
-----
Nebula Version: 1.4.0
Linux

MacOS (client)
-----
Nebula Version: 1.4.0
OS: MacOS / Darwin Kernel Version 19.6.0 / Catalina 10.15.7

Android (client)
-----
App: 0.0.41-50 (sha: 93b106f)
Nebula: 1.4.1

Linux (client)
-----
Nebula Version: 1.3.0  **-- No apparent time out**

Sample error message
-----

```
INFO[2021-08-02T16:40:43.742-10:00] Firewall rule added                           firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
INFO[2021-08-02T16:40:43.742-10:00] Firewall started                              firewallHash=b6......
INFO[2021-08-02T16:40:43.745-10:00] Main HostMap created                          network=10.1.1.1/8 preferredRanges="[]"
INFO[2021-08-02T16:40:43.745-10:00] UDP hole punching enabled
INFO[2021-08-02T16:40:44.045-10:00] Nebula interface is active                    build=1.4.0 interface= network=10.1.1.1/8 udpAddr="[::]:54540"
INFO[2021-08-02T16:40:44.053-10:00] Handshake message sent                        handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3371186316 udpAddrs="[a.b.c.d:6666]" vpnIp=10.2.2.2
INFO[2021-08-02T16:40:44.162-10:00] Handshake message received                    certName=mylighthouse durationNs=112420748 fingerprint=32... handshake="map[stage:2 style:ix_psk0]" initiatorIndex=3371186316 remoteIndex=3371186316 responderIndex=2307878206 sentCachedPackets=1 udpAddr="a.b.c.d:6666" vpnIp=10.2.2.2
INFO[2021-08-02T16:42:10.352-10:00] Handshake timed out                           durationNs=9207428700 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2336252132 remoteIndex=0 udpAddrs="[]" vpnIp=10.255.255.255
INFO[2021-08-02T16:42:27.753-10:00] Handshake timed out                           durationNs=9536335534 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1956456100 remoteIndex=0 udpAddrs="[]" vpnIp=10.255.255.255

```

**Comment by resuscv** [comment]
I _suspect_ the reason why this is not obvious in v.1.3.0 is that there is no `timed out` warning/error message.

**Comment by resuscv** [comment]
I changed to having a lighthouse on my local network.  The timed out error still occurs.

My `config.yaml` for the Mac if anyone is interested is below.  It is identical to the `config.yaml` I'm using for my linux hosts that don't have this error.

```
pki:
  ca: ./ca.crt
  cert: ./host.crt
  key: ./host.key

static_host_map:
  "10.20.0.1": ["192.168.0.1:4242"]

lighthouse:
  am_lighthouse: false
  hosts:
    - "10.20.0.1"

listen:
  host: 0.0.0.0
  port: 4242

punchy:
  punch: true

local_range: "192.168.0.0/24"

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false

logging:
  # level: info
  level: debug
  disable_timestamp: false
  timestamp_format: "2006-01-02T15:04:05.000Z07:00"

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any
```

**Comment by tahyonline** [comment]
I have observed this issue on macOS after the host woke from sleep, i.e., nebula was started before sleep and survived (?) it. The issue seems to occur between macOS hosts, affects both Big Sur and Catalina. All nebula endpoints are 1.4.0.
In three terminals:
- ping the lighthouse (Ubuntu focal LTS) nebula address: no issues, ping responds every second
- ping a Raspberry Pi (buster) nebula address: no issues, like above
- ping another macOS host's nebula address: no ping response and _all pings stop_

On the pinging host:
- nebula is completely frozen and does not recover (at least within 5-10min)
- when killed, nebula logs an entry for getting the SIGTERM, but does not actually exit
- there are no log entries for initiating the handshake to the other macOS host: there is one entry for completing the handshake to the rpi and then an entry for the SIGTEM, nothing in between
- use kill -9 to get it to quit

On the pinged host:
- there are log entries for the incoming handshake from the pinging host and then the timeout messages

**Comment by nbrownus** [comment]
This is macos doing some probing of the broadcast ip in your nebula network, you can tell by `vpnIp=10.255.255.255` in the logs (given your nebula network is `10.0.0.0/8`. The other thing to note in the logs is that `udpAddrs="[]"` is saying "I have no clue who lives at this address" because your lighthouses can't answer for it, because there is no host there.

You can tell nebula to drop broadcast packets (and avoid seeing this log message) by flipping this to true https://github.com/slackhq/nebula/blob/7801b589b6a393898f89b238c39a5a8dced1df84/examples/config.yml#L154

**Comment by turtlewax** [comment]
@nbrownus I am also seeing this error, except in my case, my lighthouse most definitely knows and has a udpAddr for my remote host and my mac host.  Trouble is, my mac nebula host doesn't seem to be able to find out about the udpAddr for the other remote host.

Here is what I see on my lighthouse:
`Nov 15 10:26:14 hostname nebula[1478]: time="2021-11-15T10:26:14-05:00" level=info msg="Handshake message sent" certName=pc1 fingerprint=2733666f6007c2b508475b269fdb332a240343c49ba36b3973c5ffc31f999151 handshake="map[stage:2 style:ix_psk0]" initiatorIndex=1797597823 issuer=298e1986b9d3e1f20316a9b3389ebb037dcfe465932453e2b25c4f949e3e0217 remoteIndex=0 responderIndex=1842167964 sentCachedPackets=0 udpAddr="<redacted public IP>:48415" vpnIp=192.168.200.3`

And here is what my mac nebula client reports:
`INFO[0868] Handshake timed out                           durationNs=9382057076 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=788921434 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.200.3`

Now, the lighthouse log absolutely shows both of these separate hosts properly, with different, correct public udpAddrs assigned for each.  The other remote host (192.168.200.3) is correctly reporting the udpAddr for the mac client, but the mac client never seems to get or find out about a udpAddr for the remote host (udpAddrs="[]", as seen above).

Why is this?  Is this a bug in the darwin nebula client that no one has reported yet?

**Comment by nbrownus** [comment]
@turtlewax OPs error is a log line indicating nebula could not find a host at the broadcast ip for their nebula network, which is expected, as there is no host actually residing at the broadcast IP for their nebula network.

It sounds like you are having a different problem, please open a new issue.

**Comment by turtlewax** [comment]
@nbrownus Done, new issue #585.  Apologies for misreading this one to begin with.
