### ISSUE TITLE
Lighthouse can connect to everything; other nodes can't connect cross-WAN

### ISSUE THREAD

**Issue by robpomeroy** [slackhq/nebula#518]
My home network uses a pfSense router to "balance" broadband and mobile data circuits. Rules on the pfSense router force my work laptop to use the 4G circuit by default, with everything else using broadband.

![image](https://user-images.githubusercontent.com/736624/131694561-7e3b6a23-1fe4-4edd-a6fb-925995fb5976.png)

Port forwarding allows internal connections to a lighthouse VM running within my LAN.  I have three nebula nodes: two at home and one on a remote (work) network.

My home machines can connect to each other, but the remote node at work cannot connect to the home nodes (and vice versa).

![image](https://user-images.githubusercontent.com/736624/131694847-ffd8486d-3721-460e-a53e-338cf8fc248c.png)

I enabled punchy > punch and punchy > respond, just in case. I temporarily disabled firewalls on all Windows nodes and enabled "allow all" inbound and outbound in the Nebula configs..

The lighthouse can connect to everything, without issue. I *believe* that when my personal and work laptops connect to each other, they are effectively routing out of the LAN and back in again (sort of like hairpin NAT), but could be wrong. I don't know if Nebula is capable of local discovery though?

I'm seeing lots of "Handshake timed out" messages in the Nebula output for the failing connections.

Is Nebula capable of routing over this network, despite the double-NAT situation (pfSense router, plus my WAN routers)? Have I missed an obvious step?

Could be duplicate of #85?

PS Given my use of pfSense, I have tried this, to no avail: https://blog.ktz.me/punching-through-nat-with-nebula-mesh/

**Comment by wildardoc** [comment]
Someone else may know better but I believe your problem is that since your
lighthouse is inside your lan, when it hands out the "here is how I talk to
the host" info to your machine at work, it is probably giving out a port
and IP that is on the lan.  The work computers wouldn't be able to use
those connection details.  However that isn't to say that if that is
cleared up that the firewall at work won't be an issue.

I'd move the lighthouse to an address outside your home and office lans
first and see if that works.

**Comment by robpomeroy** [comment]
@wildardoc I moved the lighthouse node to AWS this morning. All nodes can connect to the lighthouse, but still not to each other, alas (handshakes time out). I presume my double-NAT at home continues to present an insurmountable problem for Nebula?

Thanks for the suggestion though - it was worth trying.

What's the significance of "state:dead"? This is the node at work, behind an ordinary single DrayTek router:

```
INFO[2341] Tunnel status                                 certName=SEC-1-Win10 tunnelCheck="map[method:active state:dead]" vpnIp=192.168.120.4
```

**Comment by robpomeroy** [comment]
Huh. I brought up a second node on my home LAN and now everything can connect to everything else (without the VPN). I swear this wasn't working before (when my personal laptop was switched off).

**Comment by wildardoc** [comment]
I've noticed in the past that I've had to reset once in a while.

**Comment by robpomeroy** [comment]
@wildardoc - that was a good shout. I added an Android node over the weekend and it couldn't see any other node until I restarted the lighthouse. Weird.

**Comment by wildardoc** [comment]
I like it for home.  Everything seems good but once in a while one machine
has a problem and I reset the lighthouse and all is good again.  It would
likely redistribute the keys at that point.  If you reuse a ip with new
keys I would expect there would be issues as well.  I'm not a developer on
this I've just been using it for networking between co-workers while
teleworking since March last year.  Actually we had to leave nebula for
work and switch to a different project that handled the firewalls at the
office better.

**Comment by robpomeroy** [comment]
@wildardoc Agreed - I had a rock-solid day yesterday of fast RDP to a remote WIn10 VM, thanks to Nebula. Can't recall achieving this speed and stability with any VPN.

Since Slack is using this at (massive) scale, I assume there must be a way of fettling it such that it doesn't display these symptoms. It's a really promising start for me.

Thanks for your helpful input!
