### ISSUE TITLE
Not using IPV6 but log shows IPV6 "Error while validating outbound packet"

### ISSUE THREAD

**Issue by johnjces** [slackhq/nebula#569]
Amazing! I have things working well between two nebula Nodes, one lighthouse one client/node! I am using an RPi 4B with 64 bit RaspiOS Lite and the 64 bit ARM version of Nebula. I am however getting an error in my non-lighthouse node regarding IPV6 which I am not using and is not in any nebula or RPi config. 

time="2021-11-06T12:02:56-07:00" level=debug msg="Tunnel status" tunnelCheck="map[method:passive state:alive]" vpnIp=192.168.98.1
time="2021-11-06T12:03:22-07:00" level=debug msg="Error while validating outbound packet: packet is not ipv4, type: 6" packet="[96 0 0 0 0 8 58 255 254 128 0 0 0 0 0 0 149 15 91 189 38 49 35 217 255 2 0 0 0 0 0 0 0 0 0 0 0 0 0 2 133 0 66 96 0 0 0 0]"
time="2021-11-06T12:03:26-07:00" level=debug msg="Tunnel status" tunnelCheck="map[method:passive state:alive]" vpnIp=192.168.98.1

Of possible interest as I move between Windows and Linux, the certs were all created on my windows box and then just moved them over to the RPi.

Any thoughts?

Thanks so much!

**Comment by gadmyth** [comment]
I have the same problem in my vultr's virtual machine, under fedora 35 (5.14.16-301.fc35.x86_64)

**Comment by nbrownus** [comment]
This is a debug log line explaining why a given packet was dropped. Something on your system is probing the nebula network using ipv6 packets and nebula is just explaining that it won't be processing that packet because it's ipv6. This behavior is typical and can generally be ignored.

I wouldn't recommend running with debug logs unless you are actively debugging something.

**Comment by johnjces** [comment]
@nbrownus 

Thank-you very muhc for the reply and info!! And 10-4 on the logging. Don't want to wear out my SDCard.

John
