### ISSUE TITLE
Update Fedora Package

### ISSUE THREAD

**Issue by IceWreck** [slackhq/nebula#588]
The last copr build is from 4 months ago. https://copr.fedorainfracloud.org/coprs/jdoss/nebula/

Please update it to v1.5.0

@jdoss 

Also, how do you run nebula with SELinux enforcing ? For Fedora I can use this copr but are there any specific SELinux instructions for other distros ?
Example: In Rocky Linux nebula refuses to work with SELinux enforcing. The SeLinux logs spewed some commands to grant an exception for nebula's sytem service and thats how I got it to work there.

**Comment by jdoss** [comment]
I'll get it upgraded this weekend.

**Comment by IceWreck** [comment]
Thanks

**Comment by jdoss** [comment]
I have been trying to get this packaged but the minimum supported Go version is 1.17 and Fedora 35 only has 1.16.8. I am getting failures due to `//go:build lines` from the new version.

https://download.copr.fedorainfracloud.org/results/jdoss/nebula/fedora-34-x86_64/02990805-nebula/build.log.gz

```
+ go-rpm-integration install -i github.com/slackhq/nebula -b
/builddir/build/BUILD/nebula-1.5.0/_build/bin -s
/builddir/build/BUILD/nebula-1.5.0/_build -o
golang-github-slackhq-nebula-devel.file-list -O
/builddir/build/BUILD/nebula-1.5.0 -V 1.5.0-1.fc34 -p
/builddir/build/BUILDROOT/nebula-1.5.0-1.fc34.x86_64 -g
/usr/share/gocode -r '.*example.*'
Installing: github.com/slackhq/nebula
panic: //go:build comment without // +build comment
goroutine 1 [running]:
panic(0x564a8a71c5e0, 0xc000028d90)
```

I can revert  https://github.com/slackhq/nebula/pull/553/files and patch it as part of the package process but that might cause issues. @nbrownus what would you do here? Fedora 34 and 35 have Go 1.16.x and Fedora 36 will have 1.17 once it is released in the spring.

**Comment by wadey** [comment]
I think this is actually a bug on our side, it looks like we didn't run gofmt properly on some of the windows files, (perhaps because they don't automatically gofmt when we are developing on Linux?)

I think the issue might actually be from the `wintun` code we imported. It looks like we need to run gofmt on them to fix the build comments (it looks like `wintun/tun.go` and `wintun/device.go` are both missing them)

**Comment by wadey** [comment]
created a proposed patch in #598.

Can you try building the rpm with this patch?

**Comment by jdoss** [comment]
@wadey it built just fine with your PR 🥳 

https://copr.fedorainfracloud.org/coprs/jdoss/nebula/build/2995114/ 

I think we can close this issue now as 1.5.0 is now released on the Copr.

**Comment by IceWreck** [comment]
Thank you
