### ISSUE TITLE
Feature Request: Distribution of DNS

### ISSUE THREAD

**Issue by AquaMCU** [slackhq/nebula#66]
Is there any possibility that the lighthouse can act as a DNS server?

I want to assign my hosts in the overlay netork a domain name. Since I do not want to edit the hosts file on each client, I wonder If I can organize this using the light house.

Oliver

**Comment by zeisss** [comment]
Not a maintainer, but the lighthouse has a DNS server builtin - you can enable it by changing this line: https://github.com/slackhq/nebula/blob/master/examples/config.yml#L29

**Comment by rawdigits** [comment]
@zeisss is quite right. The DNS server will reply to queries based on the `host` named in the cert. In my personal network, I use FQDNs as the host, so instead of `server1`, I do `server1.internal.mydomain.com` and I delegate internal.mydomain.com on the public internet to my lighthouse.

This allows resolution of DNS names in nebula and acts much like a dynamic DNS system. We will improve documentation around this soon. Closing the issue, but feel free to let me know if there is further help needed.
