### ISSUE TITLE
Add Secret Scanning for Certs/Keys to Github/Gitlab 

### ISSUE THREAD

**Issue by jasikpark** [slackhq/nebula#682]
Gitlab and Github have services that will scan repos for secret material if you set it up; it might be good to have for nebula certs / keys - we could presumably detect them based on the prelude?

I'm sure there's already a PEM detector built many times over? 

- https://docs.github.com/en/code-security/secret-scanning
- https://docs.gitlab.com/ee/user/application_security/secret_detection/

**Comment by johnmaguire** [comment]
@jasikpark I was thinking about this task and when looking at Github's secret scanning partner program, they want a webhook service for validating secrets: https://docs.github.com/en/code-security/secret-scanning/secret-scanning-partner-program#joining-the-secret-scanning-program-on-github

I'm not sure this program is a good fit for Nebula CA / host private keys, since there is no authoritative party to host the webhook (i.e. private keys belong to many disparate organizations which have no relationship to the Nebula OSS project, and the private keys do not include identifying information to find an owner.)

What do you think?
