### ISSUE TITLE
Windows 10 - Fatal Error if a tunnel adapter is already in use.

### ISSUE THREAD

**Issue by ozonejunkieau** [slackhq/nebula#70]
Running on Windows 10, nebula fails with a fatal error if some tunnel adapters are already in use. 

The only relevant logs (even with debug setting) is:
`time="2019-12-05T15:14:45+11:00" level=fatal msg="Activate failed: A device attached to the system is not functioning."`

This occurs if an existing OpenVPN session (or two) is running. Terminating all OpenVPN sessions allows nebula to run as expected.

Any thoughts?

**Comment by ozonejunkieau** [comment]
Debugging this further, nebula works as expected if it is started prior to OpenVPN sessions, but attempting to start nebula after an OpenVPN session results the aforementioned error.

**Comment by sahoahfoa** [comment]
I did some digging. This issue comes up because water, the library for TUN/TAP interfaces, picks the first TUN/TAP interface it sees in the registry. Water does give you a way to select an interface by name by specifying `InterfaceName` in `PlatformSpecificParams`. A user by the name of rpooley has a [fork doing just this](https://github.com/rpooley/nebula/commit/d9b711f51015f99aed353a46c44a411799e0ba6a). 

Right now I'm using a work around to force OpenVPN to use the second adapter by specifying `dev-node "Interface Name Here"` in my .ovpn config file. No more racing to see who connects first on boot.

**Comment by rpooley** [comment]
I have forked the repository and made a small change to tun_windows.go

```
        PlatformSpecificParams: water.PlatformSpecificParams{
            ComponentID: "tap0901",
            Network:     c.Cidr.String(),
            InterfaceName: c.InterfaceName,
        },
```

and in main.go added an additional config option for the interface name, this then allows more then one OpenVPN TAP connection to be created and more then one network connection can be made:

`        config.GetString("tun.interface_name", ""),`

There are a few more changes but these will be pretty obvious and I needed to get something working quickly!

It would be good if this could be merged into the main repository.

**Comment by anedward01** [comment]
Hey @rpooley I went ahead and merged your configs with the current repository and created a pull request #293 . It's ready to be reviewed, but it is asking that you acknowledge Slack's CLA. If you could go ahead and read and accept it, we can get it ready to be merged!

**Comment by nbrownus** [comment]
We've moved to the wintun driver. This should no longer be an issue.
