### ISSUE TITLE
Ban a node from whole network

### ISSUE THREAD

**Issue by goireu** [slackhq/nebula#72]
Hi there, and thanks for open sourcing this great tool!
I'd like to submit an idea, although I don't have a clue yet about how to implement it.

Here is the use case: ban a node from the whole network.
Maintaining a synchronized blacklist in each nebula client config file can quickly turn into a nightmare.

Some options I can think about:
- As lighthouses typically are "master" nodes in the network, my idea is to add a config option to propagate lighthouses' blacklists to other nodes in the network.
- implement an OCSP-like responder in lighthouses
- add an optional OCSP client in Nebula talking to a real, independent, OCSP responder. (this probably is the quickest win)

I get the point this breaks the decentralized pattern of Nebula, but I feel large enough networks are bound to need a clean node exclusion process.

What do you think about this?

**Comment by rawdigits** [comment]
Of the three, I think the third is the most feasible. It is probably not obvious from the existing (limited) documentation, but the lighthouses are outside of the trust model in a way we would like to retain. A single compromised lighthouse cannot do much to disrupt a nebula network, because they simply return answers to queries, and do not coordinate with each other at all.

As you noticed, we do have blacklisting in the config file, which would allow this to be pushed out via a config management system, and is how we use it ourselves.

The ability for a central authority to blacklist nodes is something we've considered, but that power comes with a downside, which is potential for abuse. I am not opposed to this if there is a good solution, likely involving some kind of signed CA blacklist.

**Comment by goireu** [comment]
Thanks for the quick reply!
OCSP responses are signed, we could either use Nebula CA or an independent CA for checking OCSP responses.
Let's close this issue for now, I'll get back to you with a pull request in a few month when it is time to implement this feature (if I haven't found a better workaround in the meantime of course 😄)

**Comment by vismiktor** [comment]
Hello! Any updates on this feature? 
@goireu did you manage to find a workaround?

**Comment by goireu** [comment]
Our current workaround is a mix of short lived certificates and blacklist, nebula configuration is regularly generated and fetched from a central API.

**Comment by vismiktor** [comment]
I see. Thank you!
