### ISSUE TITLE
🐛 BUG: ssh "invalid flag" help output goes to stderr

### ISSUE THREAD

**Issue by shish** [slackhq/nebula#756]
### What version of `nebula` are you using?

1.6.1

### What operating system are you using?

mac

### Describe the Bug

ssh into nebula

`print-cert -help`: see the help output over the ssh connection, as expected

`print-cert --help`: help output goes to the daemon's stderr (not expected), and the ssh output shows the current host's certificate (not expected)

**Comment by brad-defined** [comment]
The help output goes to stderr, not stdout.
It does so because `flag.Parse()`, used to parse the SSH command, calls `flag.Usage()` on a parse error.
(You can cause this same behavior by providing any SSH command that fails to parse, like `print-cert -blahblah`)

We could modify flag.Usage() to not print help to stderr on parse failures. But this is a global function, so that would also affect the behavior of other flag error handling in Nebula, like the `./nebula` command itself, or in any program that embeds this code.
