### ISSUE TITLE
Ability to set monthly quota on relay

### ISSUE THREAD

**Issue by Hooloovoo** [slackhq/nebula#798]
Hello,

I love the idea of the new relay feature. It would be great if I could set a quota in the relay's config file and it would stop acting as a relay once it hit that.

I have a little Linode VM that I use as my Lighthouse and it comes with a free allowance and after that I have to start paying. I would like to use it as a relay for up to e.g. 500 GB a month so that I don't have an unexpected bill.

**Comment by JohnMaguire** [comment]
Hi @Hooloovoo -

The Nebula project is focused on providing highly performant and security tunneling between your devices, with simplicity as a design goal. In order to ensure a focus on security and performance it's important to keep the surface area of Nebula low. For this reason, this feature is currently considered out of scope and I'm closing this as not planned.

FWIW, such a counter inside Nebula would not be totally accurate anyway as it wouldn't be aware of other traffic on the box. I suggest looking for a more holistic networking monitoring tool for the machine in question.
