### ISSUE TITLE
Feature request: Indicate when a lighthouse is unreachable at the ERROR log level

### ISSUE THREAD

**Issue by maggie44** [slackhq/nebula#917]
### What version of `nebula` are you using?

1.7.2

### What operating system are you using?

Mac

### Describe the Bug

When a node is started but the lighthouse is unavailable/unreachable there is no warning at log level 'ERROR'. At level INFO I see:

```
INFO[0007] Handshake timed out                           durationNs=7101752416 handshake="map[stage:1 style:ix_psk0]"
```

I think there should be some sort of indicator at the ERROR log level when the lighthouse cannot be reached. It is a breaking issue and without info here we assume things are connected. 

When enabling INFO I get far too much information streamed in to the console just to be able to see timeouts to the lighthouse. 

Example logging at INFO, without starting a lighthouse:

```
./nebula -config config.yml
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: localIp: proto:0 startPort:0]"
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip: localIp: proto:1 startPort:0]"
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:443 groups:[laptop home] host: ip: localIp: proto:6 startPort:443]"
INFO[0000] Firewall started                              firewallHash=58e2e90dab9bc5d50b9e164e6b1b0cb09c5168fc46847e3b1b3a5026d4d3de63
WARN[0000] interface name must be utun[0-9]+ on Darwin, ignoring 
INFO[0000] Main HostMap created                          network=192.168.100.10/24 preferredRanges="[]"
INFO[0000] punchy enabled                               
INFO[0000] Loaded send_recv_error config                 sendRecvError=always
INFO[0000] Nebula interface is active                    boringcrypto=false build=1.7.2 interface=utun5 network=192.168.100.10/24 udpAddr="[::]:4242"
INFO[0000] Handshake message sent                        handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2960355161 localIndex=2960355161 remoteIndex=0 udpAddrs="[100.64.22.11:4242]" vpnIp=192.168.100.1
INFO[0007] Handshake timed out                           durationNs=7101752416 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2960355161 localIndex=2960355161 remoteIndex=0 udpAddrs="[100.64.22.11:4242]" vpnIp=192.168.100.1
```

Example logging at WARNING or ERROR, without starting a lighthouse:

```
./nebula -config config.yml
WARN[0000] interface name must be utun[0-9]+ on Darwin, ignoring 
```

**Comment by johnmaguire** [comment]
This feature request is slightly different than the PR which I just closed. I think that logging an error when failing to handshake to a (or perhaps to ANY) lighthouse has a lot more merit. Unfortunately there are challenges:

- Some networks intentionally run without a lighthouse (e.g. using static_host_map or calculated_remotes)
- Some networks may run with a Lighthouse, but do not need to (e.g. because calculated_remotes accounts for all nodes)
- Some networks may run with multiple Lighthouses in every node's config, such that only one needs to be accessible at once. This could be done so that any given Lighthouse can be restarted or removed without affecting the overall network. In this case, a single failure is not an error.

But perhaps more importantly, due to the way Nebula is architected, it is probably too difficult/complex to _only_ error for Lighthouses / to only error if all Lighthouses are inaccessible.

Some alternative methods of checking Nebula's health would be to use the `stats` module or SSH debug server to determine if it's connected to desired Lighthouses. Or run a ping!
