### ISSUE TITLE
Add Google Authenticator MFA to Nebula

### ISSUE THREAD

**Issue by gebv** [slackhq/nebula#994]
I'm suggesting we add a 2FA feature using Google Authenticator. Here's how it might work:

1. Generate a 2FA QR code when creating a Nebula certificate.
2. Users can scan this QR with their Google Authenticator app.
3. During connection, if the certificate has 2FA, ask for the code.

I think this would be a great security boost. Thoughts?

**Comment by beachrunner2k** [comment]
I think you need to read about and gain an understanding of PKI and public and private key cryptography.

**Comment by JohnMaguire** [comment]
Hi @gebv - this isn't really feasible with Nebula's model. In order to validate 2FA codes, the other host would need to know the TOTP seed. If this is public in the certificate, then any host can generate codes, so there is no security value.

In addition, we don't want to require interaction when forming new tunnels. This could break application functionality.

A model that might make more sense is to use a signing oracle that issues device nodes for users that are authenticated via an internal database. That authentication can include 2FA. The signing oracle could issue short-lived certificates (e.g. 1 hour, or 8 hours for a work day. Maybe 12 if you're being generous) to ensure that 2FA is performed periodically.

However, a signing oracle is outside the scope of the Nebula project.
